# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my_nbdev',
                'doc_host': 'https://twistin.github.io',
                'git_url': 'https://github.com/twistin/my_nbdev',
                'lib_path': 'my_nbdev'},
  'syms': { 'my_nbdev.core': { 'my_nbdev.core.Card': ('cards.html#card', 'my_nbdev/core.py'),
                               'my_nbdev.core.Card.__init__': ('cards.html#card.__init__', 'my_nbdev/core.py'),
                               'my_nbdev.core.Card.__str__': ('cards.html#card.__str__', 'my_nbdev/core.py')}}}