# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_cards.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../nbs/00_cards.ipynb 13
class Card: 
    "Un juego de cartas"
    def __init__(self, 
                 suit, # Un índice dentrode 'suits'
                 rank):# Un índice dentro de 'ranks'
        self.suit, self.rank= suit,rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__= __str__

